### ISSUE TITLE
Bug in file selector. Directories and/or filenames with spaces will not mount.

### ISSUE THREAD

**Issue by Tallguy297** [emartisoft/DAControlGUI#1]
There is a bug in the file selector. If I select `Ram Disk:adf/DAControlGUI.adf` then click on the Load/Change button, nothing happens. It states that a device is mounted but that's it.

If I insert quotes around whole file path & name `"Ram Disk:adf/DAControlGUI.adf"`, success.

Regards,
Alexander.

**Comment by emartisoft** [comment]
Thank you. Bug occurs because file path containing spaces. I fixed it.
