### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by Tallguy297** [emartisoft/DAControlGUI#2]
I have 2 suggestions, which could be considered issues?
1) Creating HD Floppy images. Some Amigas have HD floppy drives and this might be a good option to have?
2) Ram Disk cleanup upon exit. Delete the log file once the program exits.

Apart from that, the program works very well.
Many thanks,
Alexander.

**Comment by emartisoft** [comment]
Thanks again.
1. You can create HD floppy images. 
![resim](https://user-images.githubusercontent.com/20000674/140429315-0e7267ff-a760-436e-8f01-4fe30d836ac6.png)

2. It may be.
